---
name: Scalar-MoreUtils
version: 0.02
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: Provide the stuff missing in Scalar::Util
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Scalar::MoreUtils:
    file: lib/Scalar/MoreUtils.pm
    version: 0.02
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
